[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']

# 補完系のプラグイン
[[plugins]]
repo = 'Shougo/neco-syntax'

# 補完系のプラグイン
[[plugins]]
repo = 'ujihisa/neco-look'

# neosnipet
[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
