[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "Both"

[window.padding]
x = 4
y = 4

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[mouse]
hide_when_typing = false

[bell]
animation = "Ease"
duration = 150
color = "#ffffff"
command = { program = "afplay", args = ["/System/Library/Sounds/Ping.aiff"] }

